server:
  port: 8082
spring:
  application:
    name: forum
  resources:
    static-locations:
    -classpath:/${site.theme}/static/
    -file:./resources/${site.theme}/static/
  freemarker:
    template-loader-path:
    -classpath:/${site.theme}/templates/
    -file:./resources/${site.theme}/templates/
    cache: false
  datasource:
    url: jdbc:mysql://localhost/forum?useSSL=false&characterEncoding=utf8
    username: root
    password: root
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.formate_sql: true
    open-in-view: false

#  redis:
#    host: localhost
#    password:
#    port: 6379
#    ssl: false
#    database: 0

  mail:
    host: smtp.qq.com
    username:
    password: #这里是QQ邮箱的授权码
    port: 465
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
  data:
  elasticsearch:
    cluster-name: elasticsearch
    cluster-nodes: 127.0.0.1:9300
site:
  name: forum
  intro: <h5>bootstrap简易论坛</h5>
  baseUrl: http://localhost:8082/
  staticUrl: http://localhost:8082/static/upload/
  pageSize: 20
  uploadPath: ./resources/${site.theme}/static/upload/
  theme: default
  GA: #Google Analytics ID
  googleZZ: # google站长meta标签content值
  baiduTJ: # 百度统计ID
  baiduZZ: # 百度站长meta标签content值
  uploadType: local # local, qiniu
  cookie:
    domain: localhost
    userName: remember-me
    userMaxAge: 30
    adminUserName: admin-remember-me
    adminMaxAge: 30
  upload:
    qiniu:
      accessKey: # 七牛开发者上传的key
      secretKey: # 七牛开发者上传的密钥
      bucket: # 创建的存储空间名称
      domain: # 存储空间域名
  oauth2:
      github:
        clientId: # github申请应用的ClientId
        clientSecret: # 对应的密钥
        callbackUrl: ${site.baseUrl}/oauth2/github/callback
mail:
  register:
    subject: 注册验证码 - ${site.name}
        content: |
          <p>您好</p>
          <p>&nbsp;&nbsp;您的验证码为 <span style='color: red;'>$\{genCode!}</span> , 请在10分钟内使用！</p><br>
          <small>本邮件为系统发出，请不要回复</small>
    commentTopic:
        subject: 话题被评论 - ${site.name}
        content: |
          <p>您好</p>
          <p>&nbsp;&nbsp;$\{username!} 评论了您的话题 <a href='$\{domain!}topic/$\{topic.id}'>$\{topic.title!}</a></p>
          <div style='background-color: #fffbc1; padding: 20px; border-radius: 5px;'>$\{content!}</div><br>
          <small>本邮件为系统发出，请不要回复</small>
    replyComment:
        subject: 评论被回复 - ${site.name}
        content: |
          <p>您好</p>
          <p>&nbsp;&nbsp;$\{username!} 回复了您在话题 <a href='$\{domain!}topic/$\{topic.id}'>$\{topic.title!}</a> 下的评论</p>
          <div style='background-color: #fffbc1; padding: 20px; border-radius: 5px;'>$\{content!}</div><br>
          <small>本邮件为系统发出，请不要回复</small>

log:
  template:
    createTopic: 创建话题 <a href='/topic/$\{topic.id}' target='_blank'>$\{topic.title}</a>
    commentTopic: 评论话题 <a href='/topic/$\{topic.id}' target='_blank'>$\{topic.title}</a>
    replyComment: 回复话题 <a href='/topic/$\{topic.id}' target='_blank'>$\{topic.title}</a> 下的评论
    editTopic: 编辑话题 <a href='/topic/$\{topic.id}' target='_blank'>$\{topic.title}</a>
    deleteTopic: 删除话题 <a href='/topic/$\{topic.id}' target='_blank'>$\{topic.title}</a>
    collectTopic: 收藏话题 <a href='/topic/$\{topic.id}' target='_blank'>$\{topic.title}</a>
    deleteCollectTopic: 删除收藏的话题 <a href='/topic/$\{topic.id}' target='_blank'>$\{topic.title}</a>
    editComment: 编辑话题 <a href='/topic/$\{topic.id}' target='_blank'>$\{topic.title}</a> 下的评论
    deleteComment: 删除话题 <a href='/topic/$\{topic.id}' target='_blank'>$\{topic.title}</a> 下的评论
    upTopic: 给话题 <a href='/topic/$\{topic.id}' target='_blank'>$\{topic.title}</a> 点赞
    downTopic: 给话题 <a href='/topic/$\{topic.id}' target='_blank'>$\{topic.title}</a> 点踩
    upComment: 给话题 <a href='/topic/$\{topic.id}' target='_blank'>$\{topic.title}</a> 下的评论点赞
    downComment: 给话题 <a href='/topic/$\{topic.id}' target='_blank'>$\{topic.title}</a> 下的评论点踩